import { createOpenAI } from "@ai-sdk/openai";
import { stepCountIs, streamText, tool } from "ai";
import { z } from "zod";
import { hasTavily, tavilySearch } from "./tavily.server";
import type { ChatReply, Prediction } from "./ai.functions";

const MODEL = "gpt-4o";

const SYSTEM = `You are MediVerse AI, a careful healthcare information assistant for a product demo.
- Answer clearly and concisely in the user's language, using short paragraphs or bullets.
- Use the web_search tool for anything time-sensitive, factual, or medical guidance you should verify.
- Never give a definitive diagnosis. Always add a brief safety note and advise seeing a clinician for anything serious.
- If symptoms sound like an emergency (chest pain, stroke signs, severe bleeding, breathing trouble), tell the user to seek emergency care immediately.`;

type Source = { title: string; url: string };

function buildModel() {
  const key = process.env["OPENAI_API_KEY"];
  if (!key) return null;
  const openai = createOpenAI({ apiKey: key });
  return openai(MODEL);
}

function searchTool(sources: Source[]) {
  return tool({
    description:
      "Search the live web (Tavily) for medical, health or general information and recent sources.",
    inputSchema: z.object({
      query: z.string().describe("The search query"),
    }),
    execute: async ({ query }: { query: string }) => {
      const res = await tavilySearch(query, { maxResults: 5 });
      if (!res) return { note: "Web search unavailable (no Tavily key configured)." };
      for (const r of res.results) {
        if (r.url && !sources.some((s) => s.url === r.url)) {
          sources.push({ title: r.title, url: r.url });
        }
      }
      return {
        answer: res.answer ?? null,
        results: res.results.map((r) => ({
          title: r.title,
          url: r.url,
          snippet: r.content.slice(0, 600),
        })),
      };
    },
  });
}

const DEMO_REPLY =
  "Demo mode: live AI is not connected yet. I can still walk you through MediVerse — ask about symptom triage, report analysis, appointments or pricing. Add an OpenAI API key and Tavily API key to get real, web-grounded answers.";

export async function runAssistant(
  messages: { role: "user" | "assistant"; text: string }[],
): Promise<ChatReply> {
  const model = buildModel();
  if (!model) return { text: DEMO_REPLY, sources: [], demo: true };

  const sources: Source[] = [];
  try {
    const result = streamText({
      model,
      system: SYSTEM,
      messages: messages.map((m) => ({ role: m.role, content: m.text })),
      tools: { web_search: searchTool(sources) },
      stopWhen: stepCountIs(8),
    });

    const text = (await result.text).trim();
    return {
      text: text || DEMO_REPLY,
      sources: sources.slice(0, 5),
      demo: false,
      ...(hasTavily() ? {} : { note: "Web search off — add a Tavily API key for live sources." }),
    };
  } catch (error) {
    return {
      text: DEMO_REPLY,
      sources: [],
      demo: true,
      note: error instanceof Error ? error.message : "AI request failed",
    };
  }
}

const DEMO_PREDICTION: Prediction["conditions"] = [
  { name: "Seasonal influenza", risk: 78, why: "Sample demo output — not generated by a model." },
  { name: "Acute bronchitis", risk: 54, why: "Sample demo output — not generated by a model." },
  { name: "Migraine episode", risk: 31, why: "Sample demo output — not generated by a model." },
];

function parseJson(raw: string): unknown {
  const cleaned = raw
    .replace(/^```(?:json)?/i, "")
    .replace(/```$/, "")
    .trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start === -1 || end === -1) return null;
  try {
    return JSON.parse(cleaned.slice(start, end + 1));
  } catch {
    return null;
  }
}

const PredictionSchema = z.object({
  conditions: z
    .array(
      z.object({
        name: z.string(),
        risk: z.number(),
        why: z.string(),
      }),
    )
    .max(6),
  advice: z.string(),
});

export async function runPrediction(symptoms: string): Promise<Prediction> {
  const model = buildModel();
  if (!model) {
    return {
      conditions: DEMO_PREDICTION,
      advice:
        "Demo mode: add an OpenAI API key for real, web-grounded risk analysis. This is not medical advice.",
      sources: [],
      demo: true,
    };
  }

  const sources: Source[] = [];
  try {
    const result = streamText({
      model,
      system: `${SYSTEM}\nYou output ONLY JSON for this task.`,
      prompt: `Patient-reported symptoms: "${symptoms}".
Search the web for current clinical guidance if useful, then return ONLY a JSON object:
{"conditions":[{"name":string,"risk":number 0-100,"why":string (max 18 words)}],"advice":string (max 45 words, includes a safety note)}
Give 3-4 plausible conditions ordered by likelihood. No markdown, no extra text.`,
      tools: { web_search: searchTool(sources) },
      stopWhen: stepCountIs(6),
    });

    const parsed = PredictionSchema.safeParse(parseJson(await result.text));
    if (!parsed.success) {
      return {
        conditions: DEMO_PREDICTION,
        advice: "Could not parse the model response. Showing demo output. Not medical advice.",
        sources: sources.slice(0, 5),
        demo: true,
      };
    }

    return {
      conditions: parsed.data.conditions.map((c) => ({
        ...c,
        risk: Math.max(0, Math.min(100, Math.round(c.risk))),
      })),
      advice: parsed.data.advice,
      sources: sources.slice(0, 5),
      demo: false,
    };
  } catch (error) {
    return {
      conditions: DEMO_PREDICTION,
      advice: "Live AI is unavailable right now — showing demo output. Not medical advice.",
      sources: [],
      demo: true,
      note: error instanceof Error ? error.message : "AI request failed",
    };
  }
}
